In [40]:
import pandas as pd
import numpy as np
crimes_by_state = pd.read_excel('./data/Table_3_Crime_in_the_United_States_by_State_2016.xls', skiprows=3, skipfooter=3)

crimes_by_state = crimes_by_state.iloc[:-5,:]

crimes_by_state.head(20)
states = []
for state in crimes_by_state['State']:
    # check if state is not NA
    if state == state:
        states.append(state)

data_by_state = []
# keep only the rows where the column 'Area' has value 'State Total
for i in range(len(crimes_by_state)):
    if crimes_by_state['Area'][i] == 'State Total':
        data_by_state.append(crimes_by_state.iloc[i])

# for each row, drop the column 'State' and unn
for i in range(len(data_by_state)):
    data_by_state[i] = data_by_state[i].drop(['State', 'Unnamed: 2','Area','Unnamed: 14','Unnamed: 15'])

# append state name to each row
for i in range(len(data_by_state)):
    data_by_state[i]['State'] = states[i]

# concatenate all the rows into a single dataframe

crime_data_by_state = pd.DataFrame(data_by_state)
# drop index column
crime_data_by_state = crime_data_by_state.reset_index(drop=True)

headers = ['Population','Violent Crime','Murder and Manslaughter','Rape (Revised Defintion)','Rape (Legacy Definition)','Robbery','Aggravated Assult', 'Property Crime','Burglary', 'Larceny and Theft' ,'Motor Vehicle Theft','State']

crime_data_by_state.columns = headers

crime_data_by_state.head(20)
crime_data_by_state.to_csv('./data/crime_data_by_state.csv')




### Arrests

In [3]:
arrests_by_state = pd.read_excel("./data/Table_22_Arrest_by_State_2016.xls",skiprows=3)
arrests_by_state = arrests_by_state.iloc[:-8,:]
states = []

for state in arrests_by_state['State']:
    # check if state is not NA
    if state == state:
        states.append(state)
arrests_data_by_states=[]
for i in range(len(arrests_by_state)):
    if arrests_by_state['Unnamed: 1'][i] == 'Total all ages':
        arrests_data_by_states.append(arrests_by_state.iloc[i,:9])

arrests_data_by_states = pd.DataFrame(arrests_data_by_states)
arrests_data_by_states.drop(['State', 'Unnamed: 1'], axis = 1, inplace = True) 
arrests_data_by_states['State'] = states
arrests_data_by_states = arrests_data_by_states.reset_index(drop=True)
headers = ['Total Arrests','Violent Crime','property Crime','Murder and Manslaughter','Rape','Robbery','Aggravated Assault','State']
arrests_data_by_states.columns = headers
arrests_data_by_states.head(20)

arrests_data_by_states.to_csv('data/arrests_data_by_state.csv')

### Officers

In [4]:
officers_by_state = pd.read_excel('data/Table_26_Full_time_Law_Enforcement_Employees_by_State_by_Cities_2016.xls',skiprows=3)
officers_by_state = officers_by_state.iloc[:-1,:]

states = []

for state in officers_by_state['State']:
    # check if state is not NA
    if state == state:
        states.append(state)

data = []

temp_data = {'Population':0,'Total Officers':0}
for i in range(len(officers_by_state)):
    if not pd.isna(officers_by_state.loc[i,'State']):
        temp_data['State'] = officers_by_state.loc[i,'State']
        data.append(temp_data)
        temp_data = {'Population':0,'Total Officers':0,'State':""}
    else:
        temp_data['Population']+=officers_by_state.loc[i,'Population']
        temp_data['Total Officers'] += officers_by_state.loc[i,'Total law\nenforcement\nemployees']

data.append(temp_data)
data= data[1:]
# convert data to dataframe
officers_data_by_state = pd.DataFrame(data)
officers_data_by_state.head(20)
officers_data_by_state.to_csv('data/officers_data_by_state.csv')

### crime trends over time

In [5]:
crime_trends = pd.read_excel('data/Table_1_Crime_in_the_United_States_by_Volume_and_Rate_per_100000_Inhabitants_1997-2016.xls',skiprows=3)
crime_trends = crime_trends.iloc[:-7,:]


# only keep columns Year,	Population1,	Violent\ncrime2, Murder and\nnonnegligent \nmanslaughter, Rape\n(legacy \ndefinition)4, Aggravated \nassault, Property \ncrime, Burglary, Larceny-\ntheft
crime_trends = crime_trends.iloc[:,[0,1,2,4,8,10,12,14,16,18,20]]
headers = ['Year','Population','Violent Crime','Murder and Manslaughter','Rape','Robbery','Aggrevated Assult','Property Crime','Burglary','Larceny and Theft','Motor Vehicle Theft']
crime_trends.columns = headers
crime_trends = crime_trends.reset_index(drop=True)
crime_trends.to_csv('data/crime_trends.csv')
crime_trends.head(20)

Year   Population  Violent Crime  Murder and Manslaughter     Rape  \
0    1997  267783607.0      1636096.0                  18208.0  96153.0   
1    1998  270248003.0      1533887.0                  16974.0  93144.0   
2    1999  272690813.0      1426044.0                  15522.0  89411.0   
3    2000  281421906.0      1425486.0                  15586.0  90178.0   
4   20015  285317559.0      1439480.0                  16037.0  90863.0   
5    2002  287973924.0      1423677.0                  16229.0  95235.0   
6    2003  290788976.0      1383676.0                  16528.0  93883.0   
7    2004  293656842.0      1360088.0                  16148.0  95089.0   
8    2005  296507061.0      1390745.0                  16740.0  94347.0   
9    2006  299398484.0      1435123.0                  17309.0  94472.0   
10   2007  301621157.0      1422970.0                  17128.0  92160.0   
11   2008  304059724.0      1394461.0                  16465.0  90750.0   
12   2009  307006550.0      1325896.0                  15399.0  89241.0   
13   2010  309330219.0      1251248.0                  14722.0  85593.0   
14   2011  311587816.0      1206005.0                  14661.0  84175.0   
15   2012  313873685.0      1217057.0                  14856.0  85141.0   
16   2013  316497531.0      1168298.0                  14319.0  82109.0   
17   2014  318907401.0      1153022.0                  14164.0  84864.0   
18  20156  320896618.0      1199310.0                  15883.0  91261.0   
19   2016  323127513.0      1248185.0                  17250.0  95730.0   

     Robbery  Aggrevated Assult  Property Crime Burglary  Larceny and Theft  \
0   498534.0          1023201.0      11558475.0  2460526          7743760.0   
1   447186.0           976583.0      10951827.0  2332735          7376311.0   
2   409371.0           911740.0      10208334.0  2100739          6955520.0   
3   408016.0           911706.0      10182584.0  2050992          6971590.0   
4   423557.0           909023.0      10437189.0  2116531          7092267.0   
5   420806.0           891407.0      10455277.0  2151252          7057379.0   
6   414235.0           859030.0      10442862.0  2154834          7026802.0   
7   401470.0           847381.0      10319386.0  2144446          6937089.0   
8   417438.0           862220.0      10174754.0  2155448          6783447.0   
9   449246.0           874096.0      10019601.0  2194993          6626363.0   
10  447324.0           866358.0       9882212.0  2190198          6591542.0   
11  443563.0           843683.0       9774152.0  2228887          6586206.0   
12  408742.0           812514.0       9337060.0  2203313          6338095.0   
13  369089.0           781844.0       9112625.0  2168459          6204601.0   
14  354746.0           752423.0       9052743.0  2185140          6151095.0   
15  355051.0           762009.0       9001992.0  2109932          6168874.0   
16  345093.0           726777.0       8651892.0  1932139          6019465.0   
17  322905.0           731089.0       8209010.0  1713153          5809054.0   
18  328109.0           764057.0       8024115.0  1587564          5723488.0   
19  332198.0           803007.0       7919035.0  1515096          5638455.0   

    Motor Vehicle Theft  
0             1354189.0  
1             1242781.0  
2             1152075.0  
3             1160002.0  
4             1228391.0  
5             1246646.0  
6             1261226.0  
7             1237851.0  
8             1235859.0  
9             1198245.0  
10            1100472.0  
11             959059.0  
12             795652.0  
13             739565.0  
14             716508.0  
15             723186.0  
16             700288.0  
17             686803.0  
18             713063.0  
19             765484.0

## arrests by crime by ethnicity

In [6]:
arrests_by_crime_ethincity = pd.read_excel('data/Table_21A_Arrests_by_Race_and_Ethnicity_2016-mod.xlsx',skiprows=6)
arrests_by_crime_ethincity.head(20)
arrests_by_crime_ethincity=arrests_by_crime_ethincity.iloc[[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6]]
arrests_by_crime_ethincity.head(20)
headers = ['Type of crime','Total','White','Black','American or Alaskan Native','Asian','Hawaiian or North Pacific Ilander']
arrests_by_crime_ethincity.columns = headers
arrests_by_crime_ethincity.to_csv('data/arrests_by_crime_and_ethnicity.csv')
arrests_by_crime_ethincity.head(20)

Type of crime      Total      White      Black  \
0                                  TOTAL  8421481.0  5858330.0  2263112.0   
1   Murder and nonnegligent manslaughter     9374.0     4192.0     4935.0   
2                                  Rape3    18606.0    12571.0     5412.0   
3                                Robbery    76267.0    33095.0    41562.0   
4                     Aggravated assault   304626.0   191205.0   101432.0   
5                               Burglary   164641.0   112651.0    47991.0   
6                          Larceny-theft   833558.0   575105.0   231199.0   
7                    Motor vehicle theft    68170.0    44970.0    20955.0   
8                                  Arson     7767.0     5593.0     1813.0   
9                         Violent crime4   408873.0   241063.0   153341.0   
10                       Property crime4  1074136.0   738319.0   301958.0   

    American or Alaskan Native     Asian  Hawaiian or North Pacific Ilander  
0                     171185.0  103244.0                            25610.0  
1                        108.0     109.0                               30.0  
2                        233.0     309.0                               81.0  
3                        663.0     659.0                              288.0  
4                       6374.0    4678.0                              937.0  
5                       1613.0    1925.0                              461.0  
6                      14933.0   10277.0                             2044.0  
7                       1018.0     895.0                              332.0  
8                        218.0     120.0                               23.0  
9                       7378.0    5755.0                             1336.0  
10                     17782.0   13217.0                             2860.0

murder vicitims by race ethnicity

In [7]:
murder_victims = pd.read_excel('data/Expanded_Homicide_Data_Table_1_Murder_Victims_by_Race_Ethnicity_and_Sex_2016.xls',skiprows=4)
murder_victims = murder_victims.iloc[1:7,:]
murder_victims.head(10)
headers=["Race","Total","Male","Female","Unkown"]
murder_victims.columns = headers
murder_victims.head()
murder_victims.to_csv("data/murder_victims.csv")

murder offenders

In [8]:
murder_offenders = pd.read_excel('data/Expanded_Homicide_Data_Table_2_Murder_Offenders_by_Age_Sex_and_Race_2016-mod.xlsx')
murder_offenders=murder_offenders.iloc[:19,:10]

headers = ['Age','Total','Male','Female','Unkonwn','White','Black','Other','Unkonwn','Hispanic or latino']
murder_offenders.columns = headers
age_groups = ['9 to 18', '18 to 60', '60 and over']
murder_offenders = murder_offenders[murder_offenders['Age'].isin(age_groups)]
murder_offenders.head()
murder_offenders.to_csv('data/murder_offenders.csv')


heatmap

In [9]:
heatmap_race = pd.read_excel('data/Expanded_Homicide_Data_Table_3_Murder_Race_and_Sex_of_Vicitm_by_Race_of_Offender_2016-mod.xlsx')
heatmap_race=heatmap_race.iloc[:,:8]
headers = ['Race of victim','Total','White','Black','Other','Hispanic','Non Hispanic','Unkonwn']
heatmap_race.columns = headers
heatmap_race.head()
heatmap_race.to_csv('data/heatmap_offenders_victims_by_race')




In [10]:
heatmap_sex = pd.read_excel('data/Expanded_Homicide_Data_Table_3_Murder_Race_and_Sex_of_Vicitm_by_Sex_of_Offender_2016-mod.xlsx')
headers = ['Sex of victim','Total','Male','Female','Uknown']
heatmap_sex.columns = headers
heatmap_sex.to_csv('data/heatmap_offenders_victims_by_sex')
heatmap_sex.head()

Sex of victim  Total  Male  Female  Uknown
0         Male    4751  4260     471      20
1       Female    1913  1735     176       2
2   Unknown sex     12     8       4       0

In [11]:
import matplotlib.pyplot as plt
import geopandas as gpd


arrests by crime by ethnicity

In [22]:
arrests_by_crime_ethnicity = pd.read_csv('data-dir/arrests_by_crime_and_ethnicity.csv')
arrests_by_crime_ethnicity= arrests_by_crime_ethnicity.iloc[[1,2,3,4,5,6]]
arrests_by_crime_ethnicity.head(10)

Unnamed: 0            Type of crime     Total     White     Black  \
1           1  Murder and Manslaughter    9374.0    4192.0    4935.0   
2           2                     Rape   18606.0   12571.0    5412.0   
3           3                  Robbery   76267.0   33095.0   41562.0   
4           4       Aggravated assault  304626.0  191205.0  101432.0   
5           5                 Burglary  164641.0  112651.0   47991.0   
6           6            Larceny-theft  833558.0  575105.0  231199.0   

   American or Alaskan Native    Asian  Hawaiian or North Pacific Ilander  
1                       108.0    109.0                               30.0  
2                       233.0    309.0                               81.0  
3                       663.0    659.0                              288.0  
4                      6374.0   4678.0                              937.0  
5                      1613.0   1925.0                              461.0  
6                     14933.0  10277.0                             2044.0

In [37]:
arrests_by_crime_ethnicity = pd.read_csv('data-dir/arrests_by_crime_ethnicity_T.csv')

arrests_by_crime_ethnicity.head(20)

Type of crime  Murder and Manslaughter     Rape  \
0                              Total                   9374.0  18606.0   
1                              White                   4192.0  12571.0   
2                              Black                   4935.0   5412.0   
3         American or Alaskan Native                    108.0    233.0   
4                              Asian                    109.0    309.0   
5  Hawaiian or North Pacific Ilander                     30.0     81.0   

   Robbery  Aggravated Assault  Burglary  Larceny-theft  
0  76267.0            304626.0  164641.0       833558.0  
1  33095.0            191205.0  112651.0       575105.0  
2  41562.0            101432.0   47991.0       231199.0  
3    663.0              6374.0    1613.0        14933.0  
4    659.0              4678.0    1925.0        10277.0  
5    288.0               937.0     461.0         2044.0

In [52]:
import plotly.graph_objects as go

cols = ['Murder and Manslaughter','Rape','Robbery','Aggravated Assault','Burglary','Larceny-theft']
fig = go.Figure()
races = ['White','Black','American or Alaskan Native','Asian','Hawaiian or North Pacific Ilander']
arrests_by_crime_ethnicity[cols] = (arrests_by_crime_ethnicity[cols] - arrests_by_crime_ethnicity[cols].min()) / (arrests_by_crime_ethnicity[cols].max() - arrests_by_crime_ethnicity[cols].min())
for i in range(len(races)):
    df_temp = arrests_by_crime_ethnicity[arrests_by_crime_ethnicity['Type of crime']==races[i]]
    df_temp = df_temp[cols]
    print(df_temp.values.reshape(1,-1)[0])
    fig.add_trace(go.Scatterpolar(
        r= df_temp.values.reshape(1,-1)[0],
        theta= cols,
        fill='toself',
        name=races[i]
    ))
fig.update_layout(
polar=dict(
    radialaxis=dict(
        visible=True,
        range=[0, 1]
    )),
showlegend=True
)

fig.show()

[0.44541952 0.67422402 0.43179036 0.62652253 0.68333536 0.68917781]
[0.52493579 0.28777328 0.54322905 0.33091419 0.28949933 0.27558766]
[0.0083476  0.00820513 0.00493557 0.01790318 0.00701669 0.01550064]
[0.00845462 0.01230769 0.00488293 0.01231852 0.00891704 0.00990122]
[0. 0. 0. 0. 0. 0.]


In [54]:

heatmap_offenders_victims_by_race = pd.read_csv('data-dir/heatmap_offenders_victims_by_race.csv')
heatmap_offenders_victims_by_sex = pd.read_csv('data/heatmap_offenders_victims_by_sex.csv')
heatmap_offenders_victims_by_race = heatmap_offenders_victims_by_race.drop(columns=['Total'])
heatmap_offenders_victims_by_sex = heatmap_offenders_victims_by_sex.drop(columns=['Total'])
grouped = heatmap_offenders_victims_by_race.groupby('Race of victim').sum()
# drop column Unnamed: 0 from grouped
grouped = grouped.drop(columns=['Unnamed: 0'])

Index(['Unnamed: 0', 'White', 'Black', 'Other', 'Hispanic', 'Non Hispanic',
       'Unkonwn'],
      dtype='object')
